# Numpy Array Birleştirme (Broadcasting)

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b # iki array'i birleştirir

array([5, 7, 9])

In [6]:
v = np.ones((3,3))
v

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a

array([1, 2, 3])

In [9]:
a + v # tek boyutlu array kendisinden farklı boyuttaki array'e eklendi

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [10]:
a = np.arange(3)
a

array([0, 1, 2])

In [13]:
b = np.arange(3)[:,np.newaxis]
b

array([[0],
       [1],
       [2]])

In [17]:
a + b # burası tam olarak broadcasting'dir
# BROADCASTING GOLD RULES!
# iki array boyut sayısı olarak farklı ise boyutu az olanın boyutuna 1 ekleyerek boyutunu çoğalt
# eğer eşleşmeyen boyut sayısı varsa 1 olan boyutu diğer array'in boyutuna ayarla
# hala uyuşmazlık varsa hata üret

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [18]:
z = np.arange(3).reshape((3,1))
z

array([[0],
       [1],
       [2]])

In [19]:
y = np.arange(3)
y

array([0, 1, 2])

In [20]:
z.shape

(3, 1)

In [21]:
y.shape

(3,)

In [22]:
z + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [23]:

m = np.ones((3,2))
m

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
n = np.arange(3)
n

array([0, 1, 2])

In [29]:
m.shape

(3, 2)

In [30]:
n.shape

(3,)

In [34]:
try:
    m + n
except:
    print("Gördüğünüz gibi broadcasting olmadığı için hata var")

Gördüğünüz gibi broadcasting olmadığı için hata var
