## Numpy Eleman İşlemleri

In [2]:
import numpy as np

In [6]:
a = np.random.randint(10,size=10) # bir ile 10 arasında sayılardan oluşan 10 elemanlı

In [9]:
a

array([3, 2, 7, 6, 0, 5, 1, 5, 2, 3])

In [10]:
a[0] # ilk index

3

In [11]:
a[-1] # tersten alır indexi

3

In [14]:
a[0] = 65 # ilk indexi değiştirdik

In [25]:
a = np.random.randint(10,size=(3,5))

In [26]:
a

array([[0, 4, 4, 3, 5],
       [1, 0, 9, 0, 9],
       [3, 8, 1, 9, 8]])

In [27]:
a[0][0] # ilk satırın ilk sütunu

0

In [28]:
a[0,0] # bu şekilde de gösterilir. Yukardaki gösterimin aynısı

0

In [32]:
a[0,0] = 12 # ilk satır ilk sütun değerini değiştirdik

## Slice İşlemleri (Array Alt Kümesine Erişme)

In [36]:
a = np.arange(20,30) # tek boyutlu index oluşturduk
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
a[0:3] # ilk 3 elemanı seçer alır ve ayrı bir array oluşturur

array([20, 21, 22])

In [39]:
a[:3] # yukarısı ile aynıdır

array([20, 21, 22])

In [40]:
a[3:] # 3. indexten sonrasını seçer

array([23, 24, 25, 26, 27, 28, 29])

In [41]:
a[::2] # 0'dan başlar 2'şer 2'şer sayarak ilerler

array([20, 22, 24, 26, 28])

In [44]:
a[1::2] # 1'den başla ve 2'şer 2'şer ilerle

array([21, 23, 25, 27, 29])

* **iki boyutlu array'de slice**

In [50]:
a = np.random.randint(10,size=(5,5))
a

array([[4, 4, 7, 8, 1],
       [4, 0, 0, 3, 0],
       [9, 8, 3, 2, 9],
       [6, 0, 7, 2, 8],
       [3, 5, 7, 5, 2]])

In [55]:
a[:,0] # bütün satırları al fakat sadece ilk sütunu al. virgül öncesi satırları virgül sonrası sütunları ifade eder

array([4, 4, 9, 6, 3])

In [56]:
a[0,:] # 0. indexteki satıra erişir. VİRGÜL SONRASI SATIR VİRGÜL SONRASI SÜTUNDUR!

array([4, 4, 7, 8, 1])

In [60]:
a[:2,:3] # ilk iki satır ve ilk üç sütun alınır

array([[4, 4, 7],
       [4, 0, 0]])

In [62]:
a[0:2,0:3] # yukardaki kodun aynısıdır

array([[4, 4, 7],
       [4, 0, 0]])

In [64]:
a[::,:2] # tüm satırları seç ilk iki sütun

array([[4, 4],
       [4, 0],
       [9, 8],
       [6, 0],
       [3, 5]])

In [85]:
b = np.random.randint(10,size=(3,5))

In [67]:
b_alt_kume = b[0:2,0:3]

In [69]:
b_alt_kume

array([[7, 9, 0],
       [0, 8, 6]])

In [73]:
b_alt_kume[0,0] = 999
b_alt_kume[1,1] = 99999 # burada yaptığımız değişiklik b_alt_kume'nin asıl kümesini de etkiler

In [74]:
b_alt_kume


array([[  999,     9,     0],
       [    0, 99999,     6]])

In [75]:
b

array([[  999,     9,     0,     4,     8],
       [    0, 99999,     6,     5,     8],
       [    7,     5,     6,     7,     1]])

* **alt küme için copy fonksiyonu*

In [90]:
b_alt_kume = b[0:2,0:3].copy() # bu şekilde copy fonksiyonu kullandığımızda yukarıdakinin tam tersine elimizdeki veri seti sıfırlanmaz

In [91]:
b_alt_kume[0:0] = 12345
b_alt_kume[1:1] = 987665

In [92]:
b_alt_kume

array([[0, 6, 5],
       [8, 6, 3]])

In [93]:
b

array([[0, 6, 5, 7, 4],
       [8, 6, 3, 9, 6],
       [3, 8, 6, 0, 8]])

## Fancy Index

In [95]:
x = np.arange(0,30,3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [98]:
x_den_getir = [1,3,5] # içeri kaç numaralı indexleri istediğimizi yazıyoruz
x[x_den_getir] # asıl veri seti içerisine tanımladığımız istenilen index listesini veriyoruz bu şekilde o numaradaki indexler gelmiş olur

array([ 3,  9, 15])

* **İki Boyutta Fancy**

In [104]:
ib = np.arange(9).reshape(3,3) # iki boyutlu array oluşturduk
ib

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
satir = np.array([0,1])
sütun = np.array([1,2])

In [107]:
ib[satir,sütun] # 0. satır ve 1. sütun kesişimi 1, 1.satır ve 2. sütun kesişimi 5

array([1, 5])

In [108]:
ib

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
ib[0,[1,2]] # 0. satır ve 1. ve 2. sütunları al dedik

array([1, 2])

In [113]:
ib[0:,[1,2]] # fancy index ve slice index'i birleştirdik 0 dan başla tüm satırları seç ve 1. ve 2. sütunları seçtik

array([[1, 2],
       [4, 5],
       [7, 8]])

In [115]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
# Amaç : fancy index ile birden fazla verilmiş olan indexe erişip bu elemanları değiştirmek

In [117]:
index = np.array([0,1,2])
index

array([0, 1, 2])

In [120]:
v[index]=[10,11,12] # yukardan gelen index değerlerini 0 1 2 sana verilen index ile dğeiştir
v

array([10, 11, 12,  3,  4,  5,  6,  7,  8,  9])

## Koşullu Eleman İşlemleri

In [122]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [124]:
v > 3 # v arrayin her bir elemanını '> 3' koşulu ile karşılaştırır bize true false olarak döndürür

array([False, False, False,  True,  True])

In [126]:
v %2==0

array([False,  True, False,  True, False])

In [130]:
(v**2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [129]:
(v*2)

array([ 2,  4,  6,  8, 10])

In [132]:
(v**2) == (v*2) # bu iki array birbirine eşit mi?

array([False,  True, False, False, False])

## ufunc
* **np.equal** : eşitliği sorgular
* **np.not_equal** :
* **np.less**
* **np.less_equal**
* **np.greater**
* **np.greater_equal**

In [154]:
a = np.arange(3)
np.equal([0,1,3],a) # solda karşılaştırılacak değer, sağda karşılaştırılan

array([ True,  True, False])

In [155]:
v

array([1, 2, 3, 4, 5])

In [157]:
np.sum(v<8) # içerdeki koşulu sağlayan elemanların toplamını verir

5

In [162]:
np.sum((v >3) & (v<7)) # bu arrayde 3'ten büyük VE 7'den küçük olan elemanların sayısını verir

2

In [164]:
np.sum((v >3) | (v<7)) # # bu arrayde 3'ten büyük VEYA 7'den küçük olan elemanların sayısını verir

5

In [168]:
y = np.random.randint(10,size=(3,5))
y

array([[6, 2, 9, 2, 2],
       [7, 5, 9, 1, 7],
       [8, 0, 9, 5, 8]])

In [171]:
np.sum((y>3)&(y<10), axis=1) # satır bazında 3'ten büyük ve 10'dan küçük elemanları bastırır. ilk satırda 2, ikinci satırda 4 ve üçüncü satırda 4

array([2, 4, 4])

In [172]:
np.sum((y>3)&(y<10), axis=0) # sütun bazında 3'ten büyük ve 10'dan küçük elemanları bastırır.

array([3, 1, 3, 1, 2])

* ** all() ve any()**
* ** all()** : aynı anda
* ** any()** : en az biri

In [174]:
np.all(y>4) # y array içindeki tüm elemanlar 4'ten büyük mü

False

In [180]:
np.any(y>4) # y array içindeki elemanlardan en az biri 4'ten büyük mü

True

In [181]:
y

array([[6, 2, 9, 2, 2],
       [7, 5, 9, 1, 7],
       [8, 0, 9, 5, 8]])

In [185]:
np.all(y>4,axis=1) # satır bazında karşılaştırır

array([False, False, False])

In [183]:
np.all(y>4,axis=0) # sütun bazında

array([ True, False,  True, False, False])

In [196]:
v = np.arange(6)
v

array([0, 1, 2, 3, 4, 5])

In [197]:
v[0]


0

In [198]:
v > 3

array([False, False, False, False,  True,  True])

In [201]:
v[(v>2) & (v<9)] # içeri koşul yazdığımızda koşulu sağlayan elemanları getirir bize

array([3, 4, 5])