# Numpy Array Biçimlendirme
## Array Özelliklerine Erişme
* **ndim**  : boyut sayısı

* **shape** : boyut bilgisi

* **size**  : toplam eleman sayısı

* **dtype** : array veri tipi


In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(10,size=(10,5))
a.ndim # kaç boyut var
a.shape # boyutlar kaç eleman var, yani satılarda kaç sütunlarda kaç eleman
a.size # toplam eleman sayısı
a.dtype # array tipi

## Yeniden Şekillendirmek

In [16]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a.reshape((3,3)) # elimizdeki array'i 3'e 3 lük bir matrise çevirdik

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a = np.array([1,2,3]) # elimizde bir array var fakat bunu matrise çevirmemiz lazım
a

array([1, 2, 3])

In [19]:
a.reshape((1,3)) # bu şekilde bunu 2 boyutlu bir matrise çevirdik

array([[1, 2, 3]])

In [24]:
a[np.newaxis,:] # bu şekilde de yukardaki işlemin aynısını yapabiliriz. bunu bir sütun vektörüne(2 boyutlu matrise çeivirdik


array([[1, 2, 3]])

In [25]:
a[:,np.newaxis] # bu şekildede bir sütun vektörüne çevirebiliriz

array([[1],
       [2],
       [3]])

## Birleştirmek

In [27]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [31]:
z = np.concatenate([x,y]) # concatenate fonksiyonu ile arrayleri birleştirebiliriz

In [43]:
a = np.array([[1,2,3],[4,5,6]])

In [46]:
np.concatenate([a,a], axis=1) # 2 boyutlu arrayleri de birleştirdik
                      # axis = 1 -> birleştirme işlemini satır bazında yapmak istediğimizi belirtir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
a = np.array([1,2,3]) # boyutları birbirinden farklı array birleştirme
b = np.array([[1,2,3],[4,5,6]])

In [50]:
np.vstack([a,b]) # boyutları birbiriyle eşleşmeyen arrayleri bu şekilde birleştirirz
    # vstack -> sütun bazında eşleşmesi gerek

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [55]:
a = np.array([[1,2,3],[4,5,6]])
b= np.array([[99],[99]])

In [58]:
np.hstack([b,a]) # bu şekilde birleştirmek için satır sayıları aynı olması gerekir
   # hstack -> satır bazında eşleşmesi gerek

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

## Ayırmak

In [61]:
x = [1,2,3,4,5,6,7,8]
np.split(x,[3,5]) # 3e 5 olarak bu array'i parçaladı

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [62]:
a,b,c = np.split(x,[3,5]) # sırasıyla ilk parça a,ikinci parça b, üçüncü parça c'ye atandı

In [66]:
m = np.arange(16).reshape((4,4)) # alttaki 2 satırı alıp üstteki 2 satırın yanına eklememiz gerek diye düşünelim

In [70]:
np.vsplit(m,[2]) # index dikey bazında 2. değere karşılık gelen değere göre  parçaya ayırdı

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [79]:
ust , alt = np.vsplit(m,[2]) # ilk parca ust'e ikinci parca alt'a

In [80]:
sag,sol = np.hsplit(m,[2]) # yatay'dan 2. index'e göre keser

## Sıralama

In [83]:
v = np.array([45,23,1,67,78,43,-12,4.15])

In [84]:
np.sort(v) # küçükten büyüğe sıralar

array([-12.  ,   1.  ,   4.15,  23.  ,  43.  ,  45.  ,  67.  ,  78.  ])