# NumPy Array Oluşturma

## Listelerden Array Oluşturma

In [7]:
import numpy as np
a = np.array([11,22,33,44,51,12]) # listeden bir numpy array oluşturduk
type(a)

numpy.ndarray

In [11]:
b = np.array([3.12,4.6,1.2,4.5],dtype = 'float32') # elemanların değerlerini ön tanımlı olarak dtype ile atayabiliriz
print(b)

[3.12 4.6  1.2  4.5 ]


In [15]:
np.zeros(10,dtype=int) # np.zeroes -> ilk parametre kaç eleman oluşturulacağı, ikinci parametre ise oluşturulan elemanların tipidir

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones((2,3),dtype=int) # 2 ye 3 lük bir dizi oluşturur. 1'lerden oluşturur. ilk parametre tuple olarak dizi boyutunu alır, ikinci parametre opsiyonel tipi alır

array([[1, 1, 1],
       [1, 1, 1]])

In [27]:
np.full((2,3),5) # ilk parametre tuple olarak dizi boyurunu alır, ikinci parametre ise hangi sayıdan oluşturmak istediğimizi alır

array([[5, 5, 5],
       [5, 5, 5]])

In [29]:
np.arange(0,10,2) # ilk parametre nerden başlayacağı, ikinci parametre kaça kadar gideceği, üçüncü parametre kaçar kaçar artacağı

array([0, 2, 4, 6, 8])

In [34]:
np.linspace(0,1,30) # ilk parametre başlangıç değeri, ikinci parametre bitiş değeri, üçüncü parametre kaç sayı üretileceği. Burada dedik ki 0 ile 1 arasında 30 tane sayı üret

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [39]:
np.random.normal(0,1,(3,4)) # ortalaması 0 varyansı 1 olan 3'e 4'lük normal dağılımlı bir dizi oluştur dedik

array([[-0.00272981, -0.35324362, -0.02650663, -0.12205451],
       [-0.50891165, -0.09328425, -0.22842602,  0.44208284],
       [-0.84847441, -0.76876836, -0.45542092,  0.13077637]])

In [42]:
np.random.randint(0,10,(2,2)) # 0 ile 10 arasında 2'e 2'lik bir dizi

array([[4, 7],
       [0, 8]])

In [44]:
np.eye(3) # köşegen elemanları 1 olan 3 ölçülük ıdentity matris oluşturur

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])